language: python

notifications:
  email: false

branches:
  only:
    - travis
python:
  - "2.7"
  - "3.5"

sudo: required

install:
  - "sudo apt-get install gfortran python-liblas libblas-dev liblapack-dev libatlas-dev"
  - "pip install --upgrade pip"
  - "python setup.py install"

cache:
  apt: true
  pip: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

script: "echo foo"
