language: python

python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'

cache: pip

sudo: false

virtualenv:
  system_site_packages: true

before-install:
  - pip install six scipy numpy pandas

install: python setup.py install

#script: python test.py
