language: python

notifications:
  email: false

branches:
  only:
    - travis

python:
  - "2.7"
  - "3.5"

sudo: false

addons:
  apt:
    packages:
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev


before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install -U pip wheel setuptools
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install cython six #numpy
#  - pip install -v -U scipy
  - python -V

install:
  - python setup.py install

script:
  - cd $HOME

cache:
  directories:
    - $HOME/.cache/pip
