language: python

python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'

cache: pip

sudo: false

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - python3-scipy
      - python3-numpy
      - python3-pandas
      - python3-six

install: python3 setup.py install

#script: python test.py
