language: python

sudo: false

notifications:
  email: false

branches:
  only:
    - travis

matrix:
  - env: PYTHON_VERSION="2.7" CYTHON_VERSION="0.23.4"
      addons:
        apt:
          packages:
            - python-scipy
            - libatlas3gf-base
            - libatlas-dev

  - env: PYTHON_VERSION="3.4" CYTHON_VERSION="0.23.4"
      addons:
        apt:
          packages:
            - python3-scipy
            - libatlas3gf-base
            - libatlas-dev

install:
  - python setup.py install --quiet

cache:
  apt: true
  pip: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
