language: python

sudo: false

notifications:
  email: false

branches:
  only:
    - travis

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
#    - python-numpy
#    - python-scipy

install:
  - python setup.py install --quiet

cache:
  - apt
  - pip
  - directories:
    - $HOME/.cache/pip
