language: python
sudo: false
branches:
  only:
    - master
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
#    - libblas-dev
#    - liblapack-dev
    - gfortran
    - python-numpy
    - python-scipy
before_install:
  - sudo apt-get update -qq; sudo apt-get install python-numpy python-scipy -y
install:
  - pip setup.py install
cache:
  - apt
  - pip
  - directories:
    - $HOME/.cache/pip
