language: python

python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'

virtualenv:
    system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get -qq update
  - sudo apt-get install -qq python$TRAVIS_PYTHON_VERSION-scipy python$TRAVIS_PYTHON_VERSIONV-numpy python$TRAVIS_PYTHON_VERSION-pandas python$TRAVIS_PYTHON_VERSION-six

install: python$VIRTUAL_ENV setup.py install

#script: python test.py
