language: python

python:
- '2.7_with_system_site_packages'
- '3.3'
- '3.4'
- '3.5'
- '3.6'

cache: pip

sudo: false


before-install:
  - pip install six scipy numpy pandas

install: python setup.py install

#script: python test.py
